language: python

python: "2.7"

virtualenv:
  system_site_packages: true

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache: pip

addons:
  apt_packages:
    # Although we are installing a custom Ice 3.5 build, this package is still
    # required to install some of the runtime Ice dependencies
    - ice34-services
    - python-zeroc-ice
  postgresql: "9.3"

env:
    - USER_AGENT=Travis TEST=install
    - USER_AGENT=Travis TEST=upgrade

before_install:
  - pip install -r requirements.txt
  - pip install flake8
  - flake8 -v .

before_script:
    - psql -c "create user omero with password 'omero';" -U postgres
    - psql -c "create database omero with owner omero;" -U postgres
    - psql -c "select 1;" -U omero -h localhost omero
    - mkdir $HOME/OMERO
    - echo "config set omero.data.dir $HOME/OMERO" > $HOME/config.omero
    - echo "config set omero.db.name omero" >> $HOME/config.omero
script:
    - ./travis-build

after_failure:
    - tail -n 1000 OMERO-CURRENT/var/log/Blitz-0.log
