language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install -r dev_requirements.txt --use-mirrors
  - sudo apt-get update -qq
  - sudo apt-get install -qq ice34-services python-zeroc-ice

install: python omego/main.py -h
script:
    - nosetests -d test
