language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install -r dev_requirements.txt --use-mirrors
  - sudo apt-get update -qq
  - sudo apt-get install -qq ice34-services python-zeroc-ice

install: python omego/main.py -h

before_script:
    - psql -c "create user omero with password 'omero';" -U postgres
    - psql -c "create database omero with owner omero;" -U postgres
    - psql -c "select 1;" -U omero -h localhost omero
    - sudo mkdir /OMERO
    - sudo chown $USER:$USER /OMERO
    - wget http://cvs.openmicroscopy.org.uk/snapshots/omero/4.4.8p1/OMERO.server-4.4.8p1-ice34-b304.zip
    - unzip OMERO.server-4.4.8p1-ice34-b304.zip
    - ln -s OMERO.server-4.4.8p1-ice34-b304 OMERO-CURRENT
    - cd OMERO-CURRENT
    - bin/omero db script "" "" ome -f OMERO.sql
    - psql -h localhost -U omero omero < OMERO.sql
    - bin/omero admin start

script:
    - nosetests -d test
    - flake8 omego test

after_failure:
    - tail -n 1000 OMERO-CURRENT/var/log/Blitz-0.log
